### ISSUE TITLE
Hi !There something wrong when I run the code. I can't solve it

### ISSUE THREAD

**Issue by zhouwy-lv** [jlubars/RL-MPC-LaneMerging#1]
Traceback (most recent call last):
  File "E:/py_project/RL-MPC-LaneMerging-master/main.py", line 102, in <module>
    do_task()
  File "E:/py_project/RL-MPC-LaneMerging-master/main.py", line 22, in do_task
    rainbow.train_rainbow_all_with_lr_drop(1e6)
  File "E:\py_project\RL-MPC-LaneMerging-master\rainbow.py", line 84, in train_rainbow_all_with_lr_drop
    RainbowAgent.train(num_frames)
  File "E:\py_project\RL-MPC-LaneMerging-master\rainbow.py", line 50, in train
    experiment = SingleEnvExperiment(preset, rl_agent.env)
  File "D:\Anaconda3\Anaconda3\envs\torch-gpu\lib\site-packages\all\experiments\single_env_experiment.py", line 16, in __init__
    super().__init__(self._make_writer(agent.__name__, env.name, write_loss), quiet)
  File "D:\Anaconda3\Anaconda3\envs\torch-gpu\lib\site-packages\all\experiments\single_env_experiment.py", line 96, in _make_writer
    return ExperimentWriter(self, agent_name, env_name, loss=write_loss)
  File "D:\Anaconda3\Anaconda3\envs\torch-gpu\lib\site-packages\all\experiments\writer.py", line 28, in __init__
    'runs', ("%s %s %s" % (agent_name, COMMIT_HASH, current_time)), env_name
  File "D:\Anaconda3\Anaconda3\envs\torch-gpu\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Anaconda3\Anaconda3\envs\torch-gpu\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'runs\\_rainbow  2020-12-18 18:38:16 015056'
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

I hope to get your answer！Thanks!

**Comment by zhouwy-lv** [comment]
I haved handle it ,the error is from '2020-12-18 18:38:16 015056'. It may be there cannot be these symbols in the middle

**Comment by jlubars** [comment]
Ah. As I think you've figured out, this seems to be due to autonomous-learning-library's naming convention, combined with Windows' inability to handle such filenames. Sorry about that.

**Comment by zhouwy-lv** [comment]
It's okay.Thank you anyway!
