### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by 1079658109** [jlubars/RL-MPC-LaneMerging#4]
hi,jlubars
I'm sorry to trouble you,i need your help  when i run this command,The following error has occurred
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import ddpg
  File "D:\RL-MPC-LaneMerging-master\RL-MPC-LaneMerging-master\ddpg.py", line 11, in <module>
    from all.experiments import SingleEnvExperiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\__init__.py", line 1, in <module>
    from .run_experiment import run_experiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\run_experiment.py", line 1, in <module>
    from .single_env_experiment import SingleEnvExperiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\single_env_experiment.py", line 3, in <module>
    from .writer import ExperimentWriter
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 83, in <module>
    COMMIT_HASH = get_commit_hash()
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 74, in get_commit_hash
    result = subprocess.run(
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
![QQ截图20220406112640](https://user-images.githubusercontent.com/71641849/161889988-cf79c114-4ce3-4755-a219-c0667cb7b0e9.png)

**Comment by 1079658109** [comment]
I think it should be the cause of the installation error of the library environment autonomous-learning-library==0.5.3, but I don't know what is the cause of the error,Looking forward to your reply!!

**Comment by WiresharkIO** [comment]
True, even I'm getting the same error!!

**Comment by BigZhaoHYZ** [comment]
我目前也是这个错误

**Comment by xbv001** [comment]
> hi,jlubars I'm sorry to trouble you,i need your help when i run this command,The following error has occurred Traceback (most recent call last): File "main.py", line 10, in import ddpg File "D:\RL-MPC-LaneMerging-master\RL-MPC-LaneMerging-master\ddpg.py", line 11, in from all.experiments import SingleEnvExperiment File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments__init__.py", line 1, in from .run_experiment import run_experiment File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\run_experiment.py", line 1, in from .single_env_experiment import SingleEnvExperiment File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\single_env_experiment.py", line 3, in from .writer import ExperimentWriter File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 83, in COMMIT_HASH = get_commit_hash() File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 74, in get_commit_hash result = subprocess.run( File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 489, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 854, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。 ![QQ截图20220406112640](https://user-images.githubusercontent.com/71641849/161889988-cf79c114-4ce3-4755-a219-c0667cb7b0e9.png)

Hi, did you make it?
